# Generated by Django 5.0 on 2023-12-18 18:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('button', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('sidebar_content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('sidebar_title', models.TextField()),
                ('lan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.language')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('nav', models.JSONField()),
                ('content', models.TextField(max_length=7000)),
                ('button', models.TextField()),
                ('lan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.language')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articleno', models.IntegerField()),
                ('product', models.CharField(max_length=255)),
                ('inprice', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('instock', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.user')),
            ],
        ),
    ]
