# Generated by Django 5.0 on 2023-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='lan_id',
            new_name='lan',
        ),
        migrations.RenameField(
            model_name='terms',
            old_name='lan_id',
            new_name='lan',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lan_id',
            new_name='lan',
        ),
        migrations.AddField(
            model_name='price_article',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
