# Generated by Django 5.0 on 2023-12-19 07:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0002_rename_lan_id_price_lan_rename_lan_id_terms_lan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_article',
            name='lan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cross.language'),
        )
    ]
