# Generated by Django 5.0 on 2023-12-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0003_price_article_lan_alter_terms_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_article',
            name='lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross.language'),
        ),
    ]
