# Generated by Django 5.0 on 2023-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross', '0004_alter_price_article_lan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='button',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='sidebar_content',
            field=models.JSONField(),
        ),
    ]
